language:        node_js

os:
  - linux
#  - osx

dist:            trusty

sudo:            true

node_js:
  - "8"
  - "10"

services:
  - memcached
  - elasticsearch
  - mongodb

env:
  - DB=sqlite
  - DB=mysql
  - DB=mongodb

before_script:
  - sleep 30

before_install:
  - sudo apt-get install nginx -y
  - sudo apt-get install nodejs-legacy
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('nodefony') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql -e "create database IF NOT EXISTS nodefony;" -uroot -pnodefony
  - sudo mysql_upgrade -uroot -pnodefony
  - sudo service mysql restart
  - sudo mysql -e "GRANT ALL ON nodefony.* TO 'root'@'localhost';" -uroot -pnodefony
  - "curl -L https://raw.githubusercontent.com/nodefony/nodefony/master/.travis/bin/install.sh | /bin/sh"

branches:
  only:
  - master

cache:
  directories:
    - node_modules # NPM packages

addons:
  hosts:
    - nodefony.com
  apt:
    sources:     [ 'ubuntu-toolchain-r-test', 'mysql-5.7-trusty']
    packages:    ['libstdc++6', 'mysql-server', 'mysql-client']

install:         true

test:            true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d1095f0637a609e290a2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
