#
#        NODEFONY BUNDLE CONFIG YAML FILE 
#
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/


########## NODEFONY CONFIG BUNDLE  demoBundle  ############
name :				httpBundle
version :			"1.0"


#       
#       SERVERS HTTP 
#
#
http:                         
  maxHeadersCount:              null
  timeout:                      null            # For Keep alive spec
  responseTimeout:              30000           # In ms | 30 seconds by default

https:
  maxHeadersCount:              null
  timeout:                      null            # For keep alive spec
  responseTimeout:              30000           # In MS  |Â 30 seconds by default
  certificats:
    key:                        "/config/certificates/server.key"
    cert:                       "/config/certificates/server.crt"
    ca:                         ""
    options:
      rejectUnauthorized:       false

#                  
#       SERVERS WEBSOCKET 
#
#
websocket:
  keepaliveInterval:            20000
  keepaliveGracePeriod:         10000

websocketSecure:
  keepaliveInterval:            20000
  keepaliveGracePeriod:         10000

#                  
#       SERVERS STACTIC FILES 
#       For dev only 
#       use varnish  or similar reverse proxy caches
#
#       you can add directory for find statics file
#               name:
#                 path:                       "/mydirectory/"
#                 maxage:                     30*24*60*60*1000 # override default maxage
#
statics:
  settings:
    cache :                     true	
    maxAge:                     96*60*60          
  web:
    path:                       "/web/"
    maxage:                     30*24*60*60*1000

# 
#                   
#       SESSIONS MANAGER 
#
#               WARNING !!
#               IF YOU USE FIREWALL NODEFONY FIREWALL AUTO START SESSION 
#       
#               name            : cookies session name
#               handler         : session.storage.files | session.storage.sequelize | session.storage.memcached
#
#
#               MEMCACHED
#               https://github.com/3rd-Eden/memcached
#               only for handler  session.storage.memcached

session:
  start:                        null            #"autostart"
  use_strict_mode:              true                    
  name:                         "nodefony"
  handler:                      session.storage.files
  save_path:                    "/tmp/sessions"
  gc_probability:               1
  gc_divisor:                   100
  gc_maxlifetime:               1440
  hash_function:                "md5"           # sha1
  use_cookies:                  true           
  use_only_cookies:             true
  referer_check:                false
  cookie:
    maxAge:                     0               # like cookie_lifetime   =>seconde
    httpOnly:                   true            # don't see by script (javascript)
    secure:                     false           # https only
    signed:                     false
  memcached:
    servers:                      
      nodefony: 
        location:               nodefony.com
        port:                   11211
        weight:                 1
    options:
      debug:                    false

#
#       UPLOAD SERVICE CONFIG
#
#
upload:
  tmp_dir:                      "tmp/upload"
  max_filesize:                 10485760                # 10Mbits



