#
#        nodefony APP CONFIG YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#



#
#  FRAMEWORK NODEFONY
#
#     APP CONFIG  
name :                          AppBundle
locale :                        en_en
version :                       "Beta"

App:
  projectName:                  "nodefony" 
  projectYear:                  2016 
  locale:                       "en_en"
  authorName:                   "admin"
  authorMail:                   "admin@nodefony.com"

lang:
  en_en:                        "english"
  fr_fr:                        "franÃ§ais"

#
#  WEBPACK
#
# Assets root path is ./Resources/public
#
webpack:
  entry:
    main:                       "./js/app.js"
  watch:                        false
  devtool:                      "source-map"
  output:
    filename:                   "./assets/js/app.js"
    library:                    "app"
    libraryTarget:              "umd"

#
#       OVERRIDE  BUNDLE SEQUELIZE  
#       
#       see SEQUELIZE BUNDLE config for more options
#
#       Nodefony Database Management
#
#       By default nodefony create  connector name nodefony ( driver sqlite )
#       for manage Sessions / User 
#
#
#       here create new databases connectors 
#
#
sequelizeBundle: 
  debug:        false
#  connectors:                    
#    nodefony:
#      driver:          mysql
#      dbname:          'nodefony'
#      username:        'username'
#      password:        'password'
#      options:
#        dialect:       mysql
#        host:          localhost
#        port:          '3306'



#
#       OVERRIDE BUNDLE MONITORING
#
#       see MONITORING BUNDLE config for more options
#
#
monitoringBundle:
  debugBar:                     true
  storage:
    active:                     false                      
    requests:                   orm
  
#
#       OVERRIDE BUNDLE REALTIME 
#
#       see REALTIME BUNDLE config for more options
#
#
realTimeBundle:
  services:
    monitoring:
      type:                       tcp
      port:                       1318
      domain:                     localhost 

#
#       OVERRIDE BUNDLE HTTP 
#
#       see HTTP BUNDLE config for more options
#       
#       // SERVICES
#       statics files
#       session
#       http server
#       https server
#       upload 
#       websocket server 
#       websocket secure server 
#
#
httpBundle:
  statics:
    settings:
      cache :                     false	
      maxAge:                     0 
    web:
      path:                       "/web/"
      maxage:                     0                     #30*24*60*60*1000
  upload:
    tmp_dir:                      "tmp/upload"
    #max_filesize:                 100000               #in Bytes
  session:
    start:                        false                          # autostart || false 
    handler:                      session.storage.sequelize      # session.storage.files | session.storage.sequelize | session.storage.memcached
    #save_path:                    "./tmp/sessions"              # for session.storage.files only
    cookie:
      maxAge:                     0                              # like cookie_lifetime php  =>seconde 
    memcached:
      servers:                      
        nodefony: 
          location:               127.0.0.1
          port:                   11211
          weight:                 1
  http:
    responseTimeout:              40000
  https:
    responseTimeout:              40000
    

