#
#
#	CONFIG BUNDLE webrtcBundle 
#
#===============================================================================
#
#  Copyright Â© 2016/2017         | 
#
# ===============================================================================
#
#        GENERATE BY nodefony BUILDER YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
#
#



########## nodefony CONFIG BUNDLE  webrtcBundle  ############
name :				webrtcBundle
version:			"1.0"
locale :			en_en

#
#  WATCHERS
#    
#    watchers Listen to changes, deletion, renaming of files and directories 
#    of different components
#       
#    For watch all components 
# 
#      watch:			true
#    or 
#      watch:
#        controller:		true
#        config:                true
#        views:			true
#        translations:          true
#
watch:				true

#
#  WEBPACK CONFIG       
#
webpack:
  entry:
    main:                       "./js/webrtc.js"
  watch:                        true
  externals:
    jquery:                     "jQuery"
  devtool:                      "source-map"
  output:
    filename:                   "./assets/js/webrtc.js"
    library:                    "webrtc"
    libraryTarget:              "umd"

#
#
#	Insert here the bundle-specific configurations
#
#	You can also override config of another bundle  
#	with the name of the bundle 
#
#	example : create an other database connector
#


