#
#        nodefony BUILDER YAML FILE 
#
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#


########## NODEFONY CONFIG BUNDLE  demoBundle  ############
name :				demoBundle
locale :			en_en
version :                       "1.0"

#
#  WATCHERS
#    
#    watchers Listen to changes, deletion, renaming of files and directories 
#    of different components
#       
#    For watch all components 
# 
#      watch:			true
#    or 
#      watch:
#        controller:		true
#        config:                true
#        views:			true
#        translations:          true
#
watch:                          ~

#
#  WEBPACK CONFIG
#
#
#
webpack:
  entry:
    main:                       "./js/demo.js"
  watch:                        false
  devtool:                      "source-map"
  externals:
    jquery:                     "jQuery"
  output:
    filename:                   "./assets/js/demo.js"
    library:                    "demo"
    libraryTarget:              "umd"
 
