version: '2.1'

services:
  nodefony:
    container_name: nodefony
    build: "./2.0.3"
    volumes:
      - "./nodefony:/docker:rw"
      - "certificates:/nodefony/config/certificates:rw"
      - "nodefony:/nodefony"
    networks:
      nodefony:
        aliases:
         - docker.nodefony
    working_dir: "/nodefony"
    depends_on:
      db:
        condition: service_healthy
    #entrypoint:  "/nodefony/entrypoint.sh"
    links:
      - "db:docker.nodefony.db"
    environment:
      - "NODEFONY_ENVIRONMENT=dev"

# DATABASE
  db:
    container_name: mariadb
    image: mariadb
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "db:/var/lib/mysql:rw"
      - "./compose/database:/docker:rw"
    networks:
      nodefony:
        aliases:
         - docker.nodefony.db
    environment:
      - "MYSQL_DATABASE=nodefony"
      - "MYSQL_USER=nodefony"
      - "MYSQL_PASSWORD=nodefony"
      - "MYSQL_ROOT_PASSWORD=nodefony"
    #ports:
    #  - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "/docker/wait.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
    
# NGINX
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "./compose/nginx/nodefony.conf:/etc/nginx/conf.d/default.conf"
      - "certificates:/certificates"
      - "nodefony:/nodefony"
    networks:
       nodefony:
        aliases:
         - docker.nodefony.nginx
    depends_on:
      nodefony:
        condition: service_started
    ports:
      - "5151:80"
      - "5152:443"

# VOLUMES 
volumes:
  certificates:
    driver: local
  nodefony:
    driver: local
  db: 
    driver: local

# NETWORK
networks:
  nodefony: 
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.51.51.0/24
