#####################
#  NODEFONY FRAMEWORK
#
#       KERNEL CONFIG
system:
  domain                        : localhost             # nodefony can listen only one domain ( no vhost )  /    [::1] for IPV6 only
  domainAlias:   # domainAlias string only <<regexp>>   example ".*\\.nodefony\\.com  ^nodefony\\.eu$ ^.*\\.nodefony\\.eu$"
    - "^127.0.0.1$"
  httpPort                      : 5151
  httpsPort                     : 5152
  domainCheck                   : true
  statics                       : true
  security                      : true
  realtime                      : true
  monitoring                    : true
  documentation                 : true
  unitTest                      : true
  demo                          : true
  locale                        : "en_en"
  servers:
    protocol                    : "2.0"             #  2.0 || 1.1
    http                        : true
    https	                      : true
    ws			                    : true
    wss			                    : true
    certificats:
      key                       : "config/certificates/server/privkey.pem"
      cert                      : "config/certificates/server/fullchain.pem"
      ca                        : "config/certificates/ca/myproject-root-ca.crt.pem"
      options:
        rejectUnauthorized      : true
  devServer:
    inline                      : true
    hot                         : false
    hotOnly                     : false
    overlay                     : true
    logLevel                    : info        # none, error, warning or info
    progress                    : false
    protocol                    : https
    websocket                   : true

  #######################
  #  BUNDLES REGISTRATION
  #
  #       bundles:
  #         hello-bundle                 : "file:src/bundles/hello-bundle"
  #         my-bundle                    : "1.0.0"
  bundles                       : ~

  #################
  # SYSLOG NODEFONY
  log:
    active                      : true

#############
#  ASSETS CDN
#
#       CDN :    cdn.nodefony.com
#       or
#       CDN:
#          global: cdn.nodefony.com
#       or
#       CDN:
#         stylesheet:
#           - cdn.nodefony.com
#         javascript:
#           - cdn.nodefony.com
#         image:
#           - cdn.nodefony.fr
#         font:
#           - cdn.nodefony.fr
CDN                             : ~

#################
# ENGINE TEMPLATE
#
#       TWIG
#       https://github.com/justjohn/twig.js
templating                      : twig

############
# ENGINE ORM
#       sequelize || mongoose
orm                             : sequelize

#########################
# NODE.JS PACKAGE MANAGER
#
#       npm
#       yarn
packageManager                  : npm
